# This workflow runs QA tests for pull requests to dev branch
name: QA Tests

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

permissions:
  contents: read
  pull-requests: write

jobs:
  qa-tests:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Start API server
        run: |
          npm start &
          sleep 10
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          
      - name: Run QA tests
        run: |
          echo "Running QA tests..."
          node qa-test.js
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          
      - name: Report test results
        if: always()
        run: |
          echo "::group::Test Results"
          cat test-results.log || echo "No test results file found"
          echo "::endgroup::" 