# QA Test Workflow for main and Dev branches
name: QA Tests

# Explicitly define when this workflow should run
on:
  # Run on any PR
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - Dev
  # Run on pushes to main or Dev
  push:
    branches:
      - main
      - Dev

permissions:
  contents: read
  pull-requests: write

jobs:
  qa-tests:
    name: Run QA Tests
    runs-on: ubuntu-latest
    
    # Add debugging information
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      EVENT_NAME: ${{ github.event_name }}
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Print Debug Information
        run: |
          echo "Event name: $EVENT_NAME"
          echo "Branch name: $BRANCH_NAME"
          echo "PR number: $PR_NUMBER"
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub base ref: ${{ github.base_ref }}"

      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Start API server
        run: |
          echo "Starting API server..."
          npm start &
          echo "Waiting for server to be ready..."
          sleep 15
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NODE_ENV: production
          
      - name: Run QA tests
        run: |
          echo "Running QA tests..."
          node qa-test.js
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NODE_ENV: production
          
      - name: Report test results
        if: always()
        run: |
          echo "::group::Test Results"
          echo "Test execution completed"
          if [ -f test-results.log ]; then
            cat test-results.log
          else
            echo "No test results file found"
          fi
          echo "::endgroup::" 